#应用程序配置
Mysql:
  host: 192.168.7.232
  port: 3307
  user: cmsdev
  pass: cmsdev
  db:   cmsdev
RabbitMq:
  host: 192.168.7.198
  port: 5672
  user: admin
  pass: admin
  #回调要设置true
  publisherConfirms: false
  virtualHost: video
  #手工应答模式
  acknowledgeMode: manual
  #消费端最小并发数
  concurrency:  5
  #消费端最大并发数
  maxConcurrency:  10
  #一次请求中预处理的消息数量
  prefetch: 5
  #缓存的channel数量
  cacheChannelSize: 50